version: '3'

services:
  fastapi:
    build: fastapi/
    ports: 
      - 8000:8000
    networks:
      - deploy_network
    container_name: fastapi
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000"]
        interval: 30s
        timeout: 10s
        retries: 5

  streamlit:
    build: streamlit/
    depends_on:
      - fastapi
    links: 
        - fastapi
    restart: on-failure
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge